### ISSUE TITLE
a variation of some letters is not added

### ISSUE THREAD

**Issue by bely66** [mpcabd/python-arabic-reshaper#80] opened 2022-06-25 16:20 UTC
I found that a variation of the letters ل and م isn't added for amiri fonts
I don't know what would be the complexity or time taken to add them but I'm willing to contribute.
Attached is some pictures of the issue I'm faceing

Original Font:
حرف اللم على الصاد
<img width="219" alt="image" src="https://user-images.githubusercontent.com/29528270/175782115-87834c9c-ac64-4f0d-bbb6-860ee7b21890.png">

حرف الميم بعد الالف واللام
<img width="176" alt="image" src="https://user-images.githubusercontent.com/29528270/175782159-56224aa6-8566-4921-8681-48bc3a1aaa11.png">

Drawing using PIL and arabic-reshaper:
<img width="200" alt="image" src="https://user-images.githubusercontent.com/29528270/175782136-86b06590-96ed-4624-a601-6233f7e4eeec.png">

<img width="174" alt="image" src="https://user-images.githubusercontent.com/29528270/175782184-ca5fa385-cbcf-468a-a0f4-bfdaff7d9756.png">

There're some other examples, but I wanted to know you initial response

**Comment by mpcabd** [comment] 2022-09-21 20:34
Unfortunately I'm aware of this, it's a duplicate of #52.

**Closed by mpcabd** 2022-09-21 20:34 UTC
