### ISSUE TITLE
Import error with python 2.7.14 32bits

### ISSUE THREAD

**Issue by DemersM** [mpcabd/python-arabic-reshaper#59] opened 2020-11-20 20:17 UTC
Hi,

I have installed arabic-reshaper (version 28.8.0) using pip with a python 2.7.14 32bits installation.

However, I got the following error on import:

`import arabic_reshaper`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python27\ArcGIS10.6\lib\site-packages\arabic_reshaper\__init__.py", l
ine 3, in <module>
    from .arabic_reshaper import reshape, default_reshaper, ArabicReshaper
  File "c:\Python27\ArcGIS10.6\lib\site-packages\arabic_reshaper\arabic_reshaper
.py", line 242, in <module>
    default_reshaper = ArabicReshaper()
  File "c:\Python27\ArcGIS10.6\lib\site-packages\arabic_reshaper\arabic_reshaper
.py", line 64, in __init__
    self.configuration = auto_config(configuration, configuration_file)
  File "c:\Python27\ArcGIS10.6\lib\site-packages\arabic_reshaper\reshaper_config
.py", line 80, in auto_config
    if 'ArabicReshaper' not in configuration_parser:
TypeError: argument of type 'instance' is not iterable
```

**Comment by mpcabd** [comment] 2020-11-27 13:54
Hello,

I can't reproduce it, but probably that's due to me not having a Windows 32 bit machine. I could also see this is installed inside ArcGIS10.6, I'm not sure if that affects it. It could be due to an old or different `configparser` package installed. Unfortunately I cannot help much here as it's clearly not a problem with the reshaper itself. I'm closing this, sorrily, but wishing you good luck.

**Closed by mpcabd** 2020-11-27 13:54 UTC
